<?php

namespace AppBundle\Repository;

/**
 * EmergencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmergencyRepository extends \Doctrine\ORM\EntityRepository
{
}
