<?php

namespace AppBundle\Repository;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends \Doctrine\ORM\EntityRepository
{

    public function findRecent() {

        return $this
            ->createQueryBuilder("reports")
            ->where("reports.archive = 0")
            ->andWhere("reports.created > :date")->setParameter(":date", new \DateTime("-2 days"))
            ->orderBy("reports.id", "DESC")
            ->getQuery()
            ->execute();

    }

}
