<?php

namespace AppBundle\Repository;
use Doctrine\Common\Collections\Collection;

/**
 * VolunteerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolunteerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySkills(Collection $kills)
    {

    }
}
